---
# Routine maintenance script

# Plays
- name: Upgrade packages
  hosts: all
  become: yes
  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Clean repositories
      apt:
        autoclean: yes
        autoremove: yes
    - name: Purge repositories
      apt:
        purge: yes
    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: full

# https://www.postgresql.org/docs/12/maintenance.html
- name: PostgreSQL routine maintenance
  hosts: all
  become: yes
  tasks:
    # https://www.postgresql.org/docs/12/backup.html
    # https://stribny.name/blog/ansible-postgresql-backups/
    - name: SQL Backup
      become: yes
      become_user: postgres
      postgresql_db:
        state: dump
        name: airbods
        target: /home/postgres/airbods.sql.gz
    # https://www.postgresql.org/docs/12/routine-vacuuming.html
    - name: Vacuum
      become: yes
      become_user: postgres
      postgresql_query:
        db: airbods
        query: "VACUUM"
        autocommit: yes

- name: Delete old log files
  hosts: all
  become: yes
  tasks:
    - name: Remove old logs
      shell:
        cmd: "journalctl --vacuum-size=1G"
...
