---
- name: Load Airflow DAGs
  hosts: all
  become: yes
  become_user: airflow
  tasks:
  # https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#dag-loader-test
    - name: Load DAGs
      shell:
        cmd: "{{ airflow_bin_path }}/python {{ item }}"
      with_fileglob:
        - "{{ airflow_home }}/dags/*.py"

- name: Test Airflow DAGs
  hosts: all
  become: yes
  become_user: airflow
  tasks:
    - name: Test DAGs
      shell: "{{ airflow_bin_path }}/airflow dags test {{ item }} {{ ansible_date_time.date }}"
      loop:
        - datacake_devices
        - datacake
        - deployments
...
