---
# This playbook defines tasks to deploy the application stack

- name: Install PostgreSQL database
  hosts: all
  remote_user: root
  tasks:
    - name: Install postgresql package
      apt:
        name: postgresql
    - name: Create Airbods DB user
      user:
        name: airbods
    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started

- name: Install Redis database
  hosts: all
  remote_user: root
  tasks:
    - name: Install Redis package
      apt:
        name: redis
    - name: Ensure Redis is running
      service:
        name: redis
        state: started

# https://airflow.apache.org/docs/apache-airflow/stable/installation.html
- name: Install Apache Airflow
  hosts: all
  remote_user: root
  tasks:
    - name: Create airflow user
      user:
        name: airflow
    - name: Create Airflow group
      group:
        name: airflow
    - name: Install Airflow prerequisites
      apt:
        name:
          - freetds-bin
          - krb5-user
          - ldap-utils
          - libsasl2-2
          - libsasl2-modules
          - libssl1.1
          - locales
          - lsb-release
          - sasl2-bin
          - sqlite3
          - unixodbc
          - python3-pip
    - name: Install virtualenv
      pip:
        name: virtualenv
    - name: Install Airflow packages
      pip:
        name:
          - apache-airflow==2.1.*
          - apache-airflow-providers-postgres==1.0.*
          - apache-airflow-providers-google==3.0.*
        virtualenv: /opt/airflow
    - name: Install systemd services
      template:
        src: /etc/ansible/airflow.service.j2
        dest: "/etc/systemd/system/airflow-{{ item }}.service"
      loop: "{{ service }}"
    - name: Enable systemd services
      systemd:
        name: "airflow-{{ item }}"
        state: started
      loop: "{{ service }}"
    - name: Initialise Airflow database
      shell: /opt/airflow/bin/airflow db init
