---
- name: Test Airflow DAGs
  hosts: all
  remote_user: airflow
  tasks:
    - name: Test DAGs
      shell: "{{ airflow_bin_path }}/airflow dags test {{ item }} {{ ansible_date_time.date }}"
      loop:
        - datacake_devices
...
